name: Deploy all canaries

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        networks:
          [
            { name: "arbitrum", deploy-script: "arbitrum" },
            { name: "optimism", deploy-script: "optimism" },
            { name: "polygon", deploy-script: "polygon" },
          ]
    steps:
      - name: Check out github repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Install graph-cli
        run: yarn global add @graphprotocol/graph-cli

      - name: Login to hosted service
        run: graph auth --product hosted-service ${{ secrets.ACCESS_TOKEN }}

      - name: Deploying subgraph to ${{ matrix.networks.name }}
        run: yarn deploy:${{ matrix.networks.deploy-script }}
